[phases.setup]
nixPkgs = ["nodejs_22", "postgresql"]

[phases.build]
cmds = ["corepack enable", "pnpm install --frozen-lockfile", "pnpm db:generate", "pnpm build"]

[start]
cmd = "pnpm db:migrate && pnpm start"
